import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
     <div className="max-w-screen-xl mx-auto flex flex-col p-4">
         <Header />
         <main>
             {children}
         </main>
         <Footer />
     </div>
      </body>
    </html>
  );
}
